export const GET_ALL_POSTS = 'GET/ALL_POSTS';
export const GET_ALL_POSTS_SUCCESS = 'GET/ALL_POSTS/SUCCESS';
export const GET_ALL_POSTS_FAILED = 'GET/ALL_POSTS/FAILED';

export const SAVE_NEW_POST = 'SAVE/NEW_POST'
export const SAVE_NEW_POST_SUCCESS = 'SAVE/NEW_POST_SUCCESS'
export const SAVE_NEW_POST_FAILED = 'SAVE/NEW_POST_FAILED'
export const AFTER_SAVING_POST = 'AFTER_SAVING_POST'

export const ADD_OR_REMOVE_LIKE = 'ADD/REMOVE/LIKE_SUCCESS'
export const SINGLE_POST_LIKE_HANDLE ='ADD_OR_REMOVE_FROM_SINGLE_POST'

export const GET_USER_DATA = 'GET/USER'
export const GET_USER_DATA_SUCCESS = 'GET/USER_SUCCESS'
export const GET_USER_DATA_FAILED = 'GET/USER_FAILED'

export const GET_ALL_AUTHORS = 'GET_ALL_AUTHORS'
export const GET_ALL_AUTHORS_SUCCESS = 'GET/ALL_AUTHORS_SUCCESS'
export const GET_ALL_AUTHORS_FAILED = 'GET/ALL_AUTHORS_FALIED'

// constants for the actions that are dispatched from 
// single post page
export const GET_SINGLE_POST = 'GET/SINGLE_POST';
export const GET_SINGLE_POST_SUCCESS = 'GET/SINGLE_POST/SUCCESS';
export const GET_SINGLE_POST_FAILED = 'GET/SINGLE_POST/FAILED';
export const POST_INITIAL_STATE = 'POST/INITIAL_STATE'

export const ADD_COMMENT_REQ = 'ADD/COMMENT_REQ'
export const ADD_COMMENT_SUCCESS = 'ADD/COMMENT_SUCCESS'
export const ADD_COMMENT_FAILED = 'ADD/COMMENT_FAILED'

export const SINGLE_POST_UPDATE = 'UPDATE/SINGLE_POST'
export const SINGLE_POST_UPDATE_SUCCESS = 'UPDATE/SINGLE_POST_SUCCESS'
export const SINGLE_POST_UPDATE_FAILED = 'UPDATE/SINGLE_POST_FAILED'

export const SINGLE_POST_DELETE = 'DELETE/SINGLE_POST'
export const SINGLE_POST_DELETE_SUCCESS = 'DELETE/SINGLE_POST_SUCCESS'
export const SINGLE_POST_DELETE_FAILED = 'DELETE/SINGLE_POST_FAILED'

export const UPDATE_COMMENT = 'UPDATE/COMMENT'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE/COMMENT_SUCCESS'
export const UPDATE_COMMENT_FAILED = 'UPDATE/COMMENT_FAILED'

export const DELETE_COMMENT = 'DELETE/COMMENT'
export const DELETE_COMMENT_SUCCESS = 'DELETE/COMMENT_SUCCESS'
export const DELETE_COMMENT_FAILED = 'DELETE/COMMENT_FAILED'